### ISSUE TITLE
use core dns

### ISSUE THREAD

**Issue by w0l4i** [WhyMan1/marzban-template#4]
درود وقتی این تیک رو از داخل v2rayng  روشن میکنم که از دی ان اس هسته استفاده بشه کلا مشکل dns پیدا میکنم و هیچ سایتی باز نمیشه و هیچ جوره dns ریسالو نمیشه

**Comment by WhyMan1** [comment]
دوست عزیزم ببخش که دیر دیدم
آیا ایده ای داری مشکل از کجاست؟
