### ISSUE TITLE
سینگ باکس 

### ISSUE THREAD

**Issue by w0l4i** [WhyMan1/marzban-template#7]
با عرض درود و خسته نباشید 
رول های هسته سینگ باکس نیاز به بازنگری دارند
لطفا به اسکرین شات توجه نمایید 
![Screenshot_20241209_063808_sing-box.jpg](https://github.com/user-attachments/assets/33e1119f-aa36-44c2-8b1f-19f9b51e6852)

**Comment by WhyMan1** [comment]
سلام دوست عزیز
https://github.com/WhyMan1/marzban-template/commit/a7b2156901009e7b2d3c313ce606ad97c515a5a3
از اینجا به بعد به روز شدن
آپدیت کنین

**Comment by WhyMan1** [comment]
تست
